server:
  port:
    8081
spring:
  datasource:
    type:
      com.alibaba.druid.pool.DruidDataSource
    username:
      root
    password:
      Xo159357
    url:
      jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
logging:
  level:
    com:
      jianxilin:
        vhr_springboot:
          mapper:
            debug